rendezvous_server = '89.168.23.158:21116'
nat_type = 2
serial = 0
unlock_pin = '007dPbgOqt8egKipZ8dptvt+lTGuM='
trusted_devices = ''

[options]
access-mode = 'full'
custom-rendezvous-server = '89.168.23.158'
av1-test = 'Y'
allow-auto-update = 'Y'
